version: "3.4"
services:
  # the main image, this is the application
  app:
    build:
      context: .
      target: rbbuilder
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - .:/app
    environment:
      TWITTER_API_KEY: GYrwCH9CjcduIEAxDYHgwttZf
      TWITTER_API_SECRET: QPwn2KCED2GOSg31YRNymp1Qhu9abRWwHqS13HI6Xr3JzkBqxU

  db:
    image: "postgres:11.5-alpine"
    environment:
      POSTGRES_USER: rpginspire
      POSTGRES_PASSWORD: rpginspire
      POSTGRES_DB: rpginspire_development
    ports:
      - "6000:5432"

